# Generated by Django 2.2.1 on 2019-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss_iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
