# Generated by Django 2.2.1 on 2019-09-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnss_iot', '0002_auto_20190906_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='coord_x',
        ),
        migrations.RemoveField(
            model_name='device',
            name='coord_y',
        ),
    ]
