# Generated by Django 2.2.1 on 2019-11-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnss_iot', '0003_auto_20190907_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.TextField(),
        ),
    ]
